---
version: '2'
services:
  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd-config/:/fluentd/etc/
      - ./fluentd-out/:/fluentd-out/
    command: [
      "fluentd"
      #, "-vv"
    ]
    networks:
      - fluent-network

  fluentbit:
    image: fluent/fluent-bit:1.8.12
    volumes:
      - ./fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluentbit/input-fluentbit.json:/app/input-fluentbit.json
    networks:
      - fluent-network

networks:
  fluent-network:
    driver: bridge
